version: '3.1'

services:
  caminv-sv-autht:
    container_name: caminv-sv-auth
    image: caminv-sv-auth:latest
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env